server {
    listen 80;

    server_name nexusflow.works www.nexusflow.works;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    server_name nexusflow.works www.nexusflow.works;

    ssl_certificate     /etc/letsencrypt/live/nexusflow.works/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nexusflow.works/privkey.pem;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/ {
        proxy_pass http://backend:8080;
    }
}