server {
    listen 80;

    server_name nexusflow.works www.nexusflow.works;

    location / {
        proxy_pass http://nexusflow-frontend;
    }

    location /api/ {
        proxy_pass http://nexusflow-backend:8080;
    }
}